### ISSUE TITLE
Gem homepage docs don't match latest official release (1.5.3)

### ISSUE THREAD

**Issue by brucek** [weppos/publicsuffix-ruby#102]
ie [the homepage](https://simonecarletti.com/code/publicsuffix-ruby/) says you can call

```ruby
PublicSuffix.domain("google.com") # => "google.com"
```

but the latest release (1.5.3 - 6 mo's old) does not have that call.

I can easily add it in (or use master on github directly), but maybe it's time to cut an official release?  Thanks, this looks like a great library!

**Comment by weppos** [comment]
Master contains a major release, with several breaking changes. It's my intention to package a release as soon as possible, but I need to write some documentation first.

**Comment by brucek** [comment]
Gotcha, thanks - just wanted you to know someone out here cares :-)

**Comment by weppos** [comment]
Thanks, I appreciate it! :) I'll do my best to release it ASAP.

**Comment by weppos** [comment]
The new version is released.
