### ISSUE TITLE
Existing domain like `iki.fi` is raising error

### ISSUE THREAD

**Issue by RaVbaker** [weppos/publicsuffix-ruby#103]
But such domain exists. 

```
[1] pry(main)> PublicSuffix.parse("iki.fi")
PublicSuffix::DomainNotAllowed: `iki.fi` is not allowed according to Registry policy
[2] pry(main)> PublicSuffix.valid?("iki.fi")
=> true
[3] pry(main)> open("http://iki.fi").status
=> ["200", "OK"]
[4] pry(main)> PublicSuffix.parse("*.iki.fi")
=> #<PublicSuffix::Domain:0x007fa52a7953e8 @sld="*", @tld="iki.fi", @trd=nil>
```

Could someone explain to me why is it this way?

**Comment by RaVbaker** [comment]
Ok, I found that default value for argument `ignore_private` is different between `PublicSuffix.parse` and `PublicSuffix.valid?` methods. When it's set to `true` there is no raise of an error. 

Why is it this way?

**Comment by RaVbaker** [comment]
Also I'm curious why domain like `naver.con` is allowed (on code from MASTER) while it's not allowed on  version from ruby gems (`1.5.3`). ?

**Comment by tuexss** [comment]
I guess it's a feature as described in https://github.com/weppos/publicsuffix-ruby/blob/b66af9da847ca5f1b754bf0a2156728dd206fd3a/README.md#private-domains

But according to the amount of issues regarding this topic, I guess it would be smarter to have `ignore_private: true` for both `valid?` and `parse`.

But yeah, the reasoning for the current defaults would be interesting to hear.

**Comment by weppos** [comment]
It's correct, the feature is the "private domains".

It's definitely a bug that the values have different defaults. The default should be `false` (include all rules). I'll fix it asap.

Thanks!
