### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by tom-lord** [weppos/publicsuffix-ruby#104]
> If you don't care about private domains at all, it's more efficient to exclude them when the list is parsed:
> 
>     # Disable support for private TLDs
>     PublicSuffix::List.default = Public::Suffix.parse(File.read(Public::Suffix::DEFAULT_LIST_PATH), private_domains: false)
>     # => "blogspot.com"
>     PublicSuffix.domain("something.blogspot.com")
>     # => "blogspot.com"

For a start, the above code is invalid - my first thought was that it should now say:

    PublicSuffix::List.default = PublicSuffix.parse(File.read(PublicSuffix::List::DEFAULT_LIST_PATH), ignore_private: true)

However, attempting this gives the following error:

    // ===end private domains=== is not expected to contain a scheme
        from /home/tom/.rvm/gems/ruby-2.3.0/gems/public_suffix-2.0.1/lib/public_suffix.rb:65:in `parse'

**Comment by weppos** [comment]
Fixed, thanks.
