### ISSUE TITLE
Inconsistent validation after upgrading from 1.5.3 to 2.0.1 

### ISSUE THREAD

**Issue by sergiobayona** [weppos/publicsuffix-ruby#105]
domains that previously failed validation. i.e.:

 ``PublicSuffix.valid?('x.yz')``
``=> false``

now return ``true`` and it's unclear why.

**Comment by weppos** [comment]
That's a requirement of the official PSL algorithm.
https://github.com/weppos/publicsuffix-ruby/pull/91

**Comment by davebrace** [comment]
I ran into this as well. My solution was as follows:

```ruby
PublicSuffix.parse(domain, default_rule: PublicSuffix::Rule::Exception.new("!*"))
```

Perhaps I could open a PR to get something like this documented in the Readme?

**Comment by weppos** [comment]
@davebrace first of all let me highlight that the default PSL algorithm requires the library to behave as the current version is behaving.

That said, you can simply use:

```ruby
PublicSuffix.parse(domain, default_rule: nil)
```

**Comment by davebrace** [comment]
@weppos Good to know!

I'm glad you're enforcing the default PSL algorithm. That makes complete sense as the default. For our usage though, we want to reject anything that is not listed.

**Comment by weppos** [comment]
@davebrace on a completely separate topic, I've got a feedback about your DNS configuration for charlieapp.com. Can I ping you directly, or should I send the email to someone else?

**Comment by davebrace** [comment]
@weppos I just shot you an email. Thanks!
