### ISSUE TITLE
DomainInvalid doesn't work.

### ISSUE THREAD

**Issue by rdonmez** [weppos/publicsuffix-ruby#111]
Hello, 

When I tried the following command, the result is always true. 

PublicSuffix.parse("nic.test", ignore_private: false) 
PublicSuffix.parse("google.hhh23.cx.t123t", ignore_private: false)

It should has threw an error.

**Comment by weppos** [comment]
Your assumption is incorrect.
See https://github.com/weppos/publicsuffix-ruby/issues/105

**Comment by rdonmez** [comment]
ok, thanks Simone.
