### ISSUE TITLE
Unable to ignore PublicSuffix::DomainNotAllowed

### ISSUE THREAD

**Issue by cheynewallace** [weppos/publicsuffix-ruby#112]
I'm trying to get past an issue im having where by i'm unable to parse domains of .gov.qa 

I get  `PublicSuffix::DomainNotAllowed: gov.qa is not allowed according to Registry policy` when trying to parse the domain. 
I've tried `PublicSuffix.parse(name, ignore_private: true)` , which seems to do nothing.

I tried adding: `PublicSuffix::List.default = PublicSuffix::List.parse(File.read(PublicSuffix::List::DEFAULT_LIST_PATH), private_domains: false)` to an initializer but I get  `NameError: uninitialized constant PublicSuffix::List::DEFAULT_LIST_PATH`

What am I missing here?  Also, I assume its correct to parse that big list in an initializer right? I'll be parsing thousands of these domains a minute so I don't want to be reparsing that giant txt file over and over again.

Let me know what im doing wrong here?

Thanks

**Comment by weppos** [comment]
`gov.qa` is listed in the ICANN private section, hence even if you disable the private domains it will have no effect.
https://github.com/weppos/publicsuffix-ruby/blob/master/data/list.txt#L5639

That rule is enforced by the registry, hence there is no way to bypass it. 

Yes, if you plan to parse multiple entries, you should initialize the list once, keep it in memory and then run queries without reloading the list all the times.

Sadly, you are not doing nothing wrong. Simply, that's the way this parser work given the definition list currently bundled with.
