### ISSUE TITLE
Domain validation is wrong

### ISSUE THREAD

**Issue by strikyflo** [weppos/publicsuffix-ruby#116]
Hi,

I can validate that "-a.com" is valid domain name using PublicSuffix gem. Therefore it's absolutely not valid, according to the RFC, stackoverflow and any registrar.
Same goes with 'a-.com'

Thank you :)

**Comment by weppos** [comment]
The syntax validation of a domain name according to the RFC is beyond the scope of this library. 

See https://github.com/weppos/publicsuffix-ruby/issues/41

**Comment by vveliev** [comment]
what is the purpose of ```.valid?```

**Comment by weppos** [comment]
Have a look at https://github.com/weppos/publicsuffix-ruby/blob/master/lib/public_suffix.rb#L118

Essentially, it validates whether the input is valid _according to the PSL rules_.
