### ISSUE TITLE
Uploaded gems contain wrong version number

### ISSUE THREAD

**Issue by bk2204** [weppos/publicsuffix-ruby#121]
The gem on rubygems.org for 2.0.3 has a value of 2.0.2 in the gemspec file.  Older versions also have this: 2.0.2 says "2.0.1" and so forth.

This breaks gem2deb.

**Comment by weppos** [comment]
Hi @bk2204, thanks for pointing it out. I'm going to investigate. The packaging is an automated process, I may have to review it.

**Comment by weppos** [comment]
@bk2204 I've just downloaded the gem from RubyGems, and the version is correct:

```
--- !ruby/object:Gem::Specification
name: public_suffix
version: !ruby/object:Gem::Version
  version: 2.0.3
platform: ruby
authors:
- Simone Carletti
autorequire: 
bindir: bin
cert_chain: []
date: 2016-09-30 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
```

Can you provide me more details of where you saw the invalid versions?

**Comment by bk2204** [comment]
Here's what I'm seeing:
```
genre ok % sha256sum public_suffix-2.0.3.gem
69cf11137edc0cb78b21592e9fdc34661c4774d4359e172737aa747537f75619  public_suffix-2.0.3.gem
genre ok % gem unpack public_suffix-2.0.3.gem
Unpacked gem: '/tmp/user/1000/public_suffix-2.0.3'
genre ok % cd public_suffix-2.0.3
genre ok % grep 2.0.2 public_suffix.gemspec
# stub: public_suffix 2.0.2 ruby lib
  s.version = "2.0.2"
```

I believe that version is what gem2deb is using.

**Comment by weppos** [comment]
I confirm the issue. Oddly enough, the gem in the repo has the right version. I rewrote the packaging feature, hopefully it will fix the issue.

However, please note that the new .gemspec will have Ruby code in it (as also happens for newly created gems in Bundler), therefore whatever packaging system you use should be able to understand it. Bundler does.

**Comment by bk2204** [comment]
I don't expect that to be a problem.  gem2deb probably already handles that, and if it doesn't, I'll send a patch.
