### ISSUE TITLE
2.0.4 doesn't conform to Semver

### ISSUE THREAD

**Issue by stevendaniels** [weppos/publicsuffix-ruby#123]
The recent 2.0.4 release doesn't conform to [SemVer](http://semver.org/)
https://github.com/weppos/publicsuffix-ruby/commit/0d52a1ba2d3600bb77364ec36d73e842de0dc072#diff-18742d7d3f5c482249adee58c0722c58

Specifically, `2.0.4` requires ruby >= 2.0; `2.0.3` doesn't have a ruby version requirement.

**Comment by weppos** [comment]
@stevendaniels that's incorrect, Ruby 1.x was dropped on version 2 of the library, in 2014.
See https://github.com/weppos/publicsuffix-ruby/commit/e39a3d7023475da6052b83cd9f676fd6ee5b9032 and https://github.com/weppos/publicsuffix-ruby/commit/0d52a1ba2d3600bb77364ec36d73e842de0dc072#diff-18742d7d3f5c482249adee58c0722c58

**Comment by dentarg** [comment]
actually, it looks like it was v1.5.0 that dropped Ruby 1.x

https://github.com/weppos/publicsuffix-ruby/blob/master/CHANGELOG.md#release-150

https://github.com/weppos/publicsuffix-ruby/commit/e39a3d7023475da6052b83cd9f676fd6ee5b9032

https://github.com/weppos/publicsuffix-ruby/compare/v1.4.6...v1.5.0

(Related to #127)
