### ISSUE TITLE
Public Blog List?

### ISSUE THREAD

**Issue by BillyParadise** [weppos/publicsuffix-ruby#125]
Hi, excellent tool.

Is there a functionality to define a second list?  I'm using this gem to separate domains of control, and I'd like to be able to add public blog sites like *.wordpress.com *.tumblr.com etc

If not, I'll fork, but if it's already possible, please let me know.

Thanks!

**Comment by dentarg** [comment]
@BillyParadise you can add rules to the list with the `#add` method: http://www.rubydoc.info/gems/public_suffix/2.0.4/PublicSuffix/List#add-instance_method

You can look at https://github.com/twingly/twingly-url/blob/v5.0.1/lib/twingly/public_suffix_list.rb as an example on extending the list :)

**Comment by BillyParadise** [comment]
wow, tab still open, you're fast!

Thanks very much.
