### ISSUE TITLE
Raise distinct exceptions

### ISSUE THREAD

**Issue by samnissen** [weppos/publicsuffix-ruby#131]
This is a feature request to raise different distinct exceptions for meaningfully different scenarios

1. ICANN domains
2. Private domains
3. Actually invalid domains

**Comment by weppos** [comment]
Can you clarify the scenarios 1 and 2?

**Comment by samnissen** [comment]
Gladly.

ICANN
```ruby
> PublicSuffix.parse(URI.parse("http://engine.aero").host).domain 
 => PublicSuffix::DomainIsICANN: engine.aero is an ICANN-protected domain
```

Private
```ruby
> PublicSuffix.parse(URI.parse("http://blogspot.com").host).domain 
 => PublicSuffix::DomainIsPrivate: blogspot.com is a private domain
```

Invalid (illogical)
```ruby
> PublicSuffix.parse(URI.parse("http://asdf").host).domain 
 => PublicSuffix::DomainNotAllowed: asdf is not allowed according to Registry policy
```

**Comment by weppos** [comment]
What is the purpose of this difference? Can you show me an example of how you plan to handle these cases (1, 2) differently?

**Comment by samnissen** [comment]
Here's a simplified version of what I would like to do

User A is allowed to CRUD any logical domain
User B is allowed to CRUD any logical domain, excluding IANA domains
User C is allowed to CRUD any logical domain, excluding IANA and private domains

Domain column applies custom `domain: true` validation that tries to parse the the domain and returns true if it parses, or adds an error if it does not, except if the current user is users A or B and if the error class is `DomainIsPrivate` or if the current user is user A if the error class is `DomainIsIANATLD` it returns true.

**Comment by weppos** [comment]
You can't exclude IANA TLDs, this library would not make sense at all without them. Also, as I explained in #132, this library doesn't perform formal validation therefore `foo_bar.com` would be valid.

If what you are trying to achieve with this library is validating a domain, then this is probably not the correct library. You should probably use https://rubygems.org/gems/addressable or the `URI` stdlib package.

**Comment by samnissen** [comment]
Will do -- thanks for your consideration.
