### ISSUE TITLE
Allow users to parse private and ICANN domains

### ISSUE THREAD

**Issue by samnissen** [weppos/publicsuffix-ruby#132]
This is a feature request to allow users to optionally parse private and ICANN domains, something like:

```ruby
> PublicSuffix.parse(URI.parse("http://blogspot.com").host).domain 
 => PublicSuffix::DomainNotAllowed: is not allowed according to Registry policy
> PublicSuffix.parse(URI.parse("http://blogspot.com").host, {:allow_private => true}).domain 
 => "blogspot.com"
> PublicSuffix.parse(URI.parse("http://engine.aero").host, {:allow_private => true, :allow_icann => true}).domain 
 => "engine.aero"
```

**Comment by weppos** [comment]
The first and second options are already valid. I don't really understand the use case for the third.

**Comment by samnissen** [comment]
Perhaps not the intended use case, but I use PublicSuffix parsing as a way of validating that user input domains are valid. If the user points to a domain that exists, but "is ICANN" (whatever that means -- not trying to be snarky, I really do not know), I don't consider that invalid. Hence, I would like PublicSuffix to raise errors _only_ when the domain actually doesn't make sense, and it's not the case that it matched a list. As far as I can tell the two 'lists' that PublicSuffix is checking otherwise valid domains against are 'ICANN' and 'private'. Hope that clarifies!

**Comment by weppos** [comment]
> but I use PublicSuffix parsing as a way of validating that user input domains are valid

If your intent is to validate whether the input is a formally valid domain name as per RFC definition, than this is definitely not the correct library. In fact, `foo_bar.com` would return success, whereas is not a valid domain name as `_` is not allowed in a domain name.

As regarding the meaning of the ICANN and private section, you may want to take a look at
https://publicsuffix.org/

I'm rejecting this request as taking our ICANN TLDs would defeat the purpose of this library and the PSL.
