### ISSUE TITLE
data/list.txt and test/tests.txt licenses

### ISSUE THREAD

**Issue by voxik** [weppos/publicsuffix-ruby#137]
The data/list.txt header states the file is licensed under Mozilla Public License, v. 2.0 and test/tests.txt refers to public domain. Shouldn't this be mentioned somewhere along other license information in README and in .gemspec "licenses" field? Would you mind to include the MPLv2 license file?

Since your gem is going to be require by RoR 5.1, I am trying to package it for Fedora and Fedora Guidelines [[1]] encourages me to ask you for this.

Thx for your help.

[1]: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

**Comment by weppos** [comment]
The Gemspec licenses section refers to the license adopted for the lib (or at least this is my current interpretation), and in fact is correctly contains MIT that is the license adopted for this project.

The "Mozilla Public License" applies exclusively to the [PSL (the list itself)](https://publicsuffix.org/list/).

I can add a mention to the README. Would that be sufficient for you?

**Comment by voxik** [comment]
In RPM world, the "license" field lists all licenses of all files included in the package. I can't see any reason why it should be different for gems. Unfortunately there is no governance body which could provide answer for the gem case, so I leave it up to you.

But listing the licenses in README would definitely help. Thx.

**Comment by weppos** [comment]
Sorry for the delay. I added the info to the README.
