### ISSUE TITLE
Not working on random url input

### ISSUE THREAD

**Issue by abender777** [weppos/publicsuffix-ruby#139]
Hi there, I was wondering if I am doing it wrong? It seems to accept anything random that at least has a . in it:

Example

2.3.0 :067 > PublicSuffix.valid?("asdg.324.asad324")
 => true

**Comment by abender777** [comment]
Another example: 
2.3.0 :071 > PublicSuffix.valid?("12gdf3.1234578")
 => true

**Comment by dentarg** [comment]
You need to override the default `*` (wildcard) rule:

```ruby
irb(main):005:0> PublicSuffix.valid?("asdg.324.asad324", default_rule: nil)
=> false
```

See https://github.com/weppos/publicsuffix-ruby/blob/f6132e1cb96080f60a0b4b1628408dc8de51e8d2/2.0-Upgrade.md#upgrade for more info about that

**Comment by abender777** [comment]
Ah great thanks! so if I use the default_rule : nil ...I will be able to stop people inputting urls that are not known to the list? Which should cover pretty much everything?

**Comment by weppos** [comment]
From https://publicsuffix.org/list/

> If no rules match, the prevailing rule is "*".

Therefore, if you enter a random string with a dot in it, the last part is considered the suffix regardless whether the suffix is in the list or not. This is by design.

This library is not designed for URL validation.

**Comment by abender777** [comment]
Appreciate the clarification, thanks!
