### ISSUE TITLE
need help understanding PublicSuffix::DomainNotAllowed

### ISSUE THREAD

**Issue by jaredmcqueen** [weppos/publicsuffix-ruby#141]
`ignore_private: true` for "example.s3.amazonaws.com"
```
tld: com
sld: amazonaws
trd: example.s3
domain: amazonaws.com
subdomain: example.s3.amazonaws.com
```

`ignore_private: false` for "example.s3.amazonaws.com"
```
    PublicSuffix::DomainNotAllowed: example.s3.amazonaws.com is not allowed according to Registry policy
```

I understand `s3.amazonaws.com` is in the private section of the list, but it behaves differently than other entries also in the private section - like `blogspot.com`.  `example.blogspot.com` should behave identically, but it doesn't.  Why would I get the DomainNotAllowed exception on one private entry, but not another?

**Comment by weppos** [comment]
It depends on the version of the list you are running, but I assume the issue you are facing is because your list (which is likely the one packaged with the release 2.0.5) contains

    *.s3.amazonaws.com

That causes the hostname you provided to be invalid. There is no such wildcard for blogspot.
