### ISSUE TITLE
Causes errors in Logstash

### ISSUE THREAD

**Issue by OmniaK87** [weppos/publicsuffix-ruby#142]
Hi guys,

This is more a comment letting you know about or needing help with an issue.  In the most recent Logstash version this is used by one of the gems.  Unfortunately it syntax errors a lot.  In function definitions any use of something like "list: List.default", the colon operator causes a syntax error of tLABEL.  It can be fixed by replacing the : by an =.  As well any use of the **options causes a syntax error tPOW as well.   

I do not know if this is an issue with my environment or jruby 1.9 or what, but figured I should let you know/ask the question.  

Thanks!

**Comment by weppos** [comment]
This library uses Ruby keyword arguments, that are available in Ruby >= 2.0. The minimum requirement for this library is currently Ruby 2.0 (or equivalent).

In the next release, the minimum Ruby version will be bumped to 2.1.
https://github.com/weppos/publicsuffix-ruby/blob/master/public_suffix.gemspec#L15

We do not support Ruby 1.9. The Ruby development team has already discontinued 2.0 and 2.1
https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/

You are encouraged to upgrade your Ruby environment.

**Comment by weppos** [comment]
I've just noticed you mentioned jRuby. This library is compatible with jRuby 9.0 or greater, as that version supports 2.x syntax.
https://travis-ci.org/weppos/publicsuffix-ruby
