### ISSUE TITLE
Validation issue in PublicSuffix

### ISSUE THREAD

**Issue by Vigneshbalakrishnan118** [weppos/publicsuffix-ruby#150]
![screen shot 2018-05-17 at 7 28 00 pm](https://user-images.githubusercontent.com/39376827/40182198-7c0b17f6-5a08-11e8-956b-f8e01149c6cd.png)
This is the query

![screen shot 2018-05-17 at 7 29 23 pm](https://user-images.githubusercontent.com/39376827/40182407-f282c55a-5a08-11e8-9863-570aa33a6090.png)

But this is the actual result

The issue is that even though if we give PublicSuffix("www........google........com"), it returns true

FYI please check the screenshots attached

**Comment by weppos** [comment]
The syntax validation of a domain name according to the RFC is beyond the scope of this library.

See #41
