### ISSUE TITLE
Can PublicSuffix::List impliment enumerable?

### ISSUE THREAD

**Issue by thesecretmaster** [weppos/publicsuffix-ruby#152]
It's be awesome to just be able to treat a list like an array.

**Comment by dentarg** [comment]
I think this is already the case, see `#each`:

https://github.com/weppos/publicsuffix-ruby/blob/8bbd236f0ca8ec137cb071c7ecf6a52198d1c497/lib/public_suffix/list.rb#L123-L130

```ruby
$ irb -rpublic_suffix
irb(main):001:0> PublicSuffix::VERSION
=> "3.0.2"
irb(main):002:0> PublicSuffix::List.new.each
=> #<Enumerator: #<Enumerator::Generator:0x00007fb07a9a5d08>:each>
irb(main):003:0> PublicSuffix::List.new.each.methods - Object.methods
=> [:size, :each, :each_with_index, :each_with_object, :next, :rewind, :with_index, :with_object, :next_values, :peek_values, :peek, :feed, :max, :min, :to_a, :to_h, :find, :entries, :sort, :sort_by, :grep, :grep_v, :count, :detect, :find_index, :find_all, :select, :reject, :collect, :map, :flat_map, :collect_concat, :inject, :reduce, :partition, :group_by, :first, :all?, :any?, :one?, :none?, :minmax, :min_by, :max_by, :minmax_by, :member?, :reverse_each, :each_entry, :each_slice, :each_cons, :zip, :take, :take_while, :drop, :drop_while, :cycle, :chunk, :slice_before, :slice_after, :slice_when, :chunk_while, :sum, :uniq, :lazy]
```

**Comment by thesecretmaster** [comment]
Well, if there's an `#each` method already defined, you can just `include Enumerable` to get all the other standard enumerable methods on the `PublicSuffix::List` object like map, select, reject, sort_by, etc. Having `#each` return an enumerator seems weird to me, because then you end up with `PublicSuffix::List.new.each.map`. You could drop the `Enumerator.new` call in `#each` and `include Enumerable`, and I think that'd be much neater. So repalce the block you've quoted with:

```ruby
include Enumerable

def each(&block)
  @rules.each do |key, node|
    y << entry_to_rule(node, key)
  end.each(&block)
end
```

**Comment by weppos** [comment]
List doesn't implement Enumerable anymore on purpose 958ecfa500d08c393e353a81b37994a04ec056b2
