### ISSUE TITLE
`elb.amazonaws.com` is not allowed according to Registry policy

### ISSUE THREAD

**Issue by ttrmw** [weppos/publicsuffix-ruby#165]
Hey! 

We're finding this domain and any subdomains are throwing this `DomainNotAllowed` error, but this does not seem correct. We're not ignoring private.

**Comment by weppos** [comment]
Hello, this is indeed correct according to this rule.
https://github.com/weppos/publicsuffix-ruby/blob/3d6b74cead4f72fbf980450ecb55ed33137bca21/data/list.txt#L10735-L10738
