### ISSUE TITLE
Similar list than publicsuffix, but for path

### ISSUE THREAD

**Issue by lwouis** [weppos/publicsuffix-ruby#184]
Hi,

We use this gem to discriminate regular subdomains (e.g. `mail.google.com`) from platforms providing subdomains for their user (e.g. `my-great-blog.blogspot.com`). This gem is great for that task.

Some large platforms don't use subdomains, but instead use the `path` to host contents from their users (e.g. `instagram.com/deliveroo`, `facebook.com/deliveroo.uk`, `twitter.com/Deliveroo`).

Another use-case for the path is URL shorteners (e.g. `goo.gl`, `bit.ly`). For these, I found [this list](https://github.com/sambokai/ShortURL-Services-List), but it doesn't have serious backing like publicsuffix.

Are you aware of a list similar to what publicsuffix is providing, but for domains hosting user-content using the `path` instead of `subdomains`?

Thank you!

**Comment by weppos** [comment]
Hi @lwouis, I am sorry, but I am not aware of any project for path-based recognition. The scope of the PSL is based on the fact domains have a special name and treatment in browsers and clients, therefore the PSL has a use case. I can't foresee how it would be done the same for paths.
