### ISSUE TITLE
Error while parsing few domains

### ISSUE THREAD

**Issue by shweta-ms** [weppos/publicsuffix-ruby#218]
👋 team
i'm from github education org. I had a query related to subdomain fetching after providing domain of email ids. We have been getting requests from valid mail IDs (like: abc@mil.no or abc@my.id from indonasian folks) but the gem returns error saying that "`abc@my.id` is not allowed according to registry policy."
 

because of this we are facing some issues with the product and wanted to bring this to your notice. 
We would like to know the reason why this is not allowed and if it is valid then may we please update in the gem and get update from your end?

**Comment by weppos** [comment]
Both suffixes are listed as public suffixes, see for instance https://github.com/weppos/publicsuffix-ruby/blob/0432e0750fa7dfcee20daf2bc44a2c40d92256b5/data/list.txt#L1307

That's the reason of the output.

If this is causing issues to you, it is possible you are using the gem incorrectly to perform a validation outside the scope of the PSL. I can't enter into the details as I am now aware of how you are using this lib.

**Comment by shweta-ms** [comment]
Found this similar scenario in the issues of this repo (https://github.com/weppos/publicsuffix-ruby/issues/19#issue-5493099)

it says that 
> It seems that it could not be fixed, because te.ua is domain zone.

So should we expect that 'mil.no' and my.id' will return errors?

**Comment by weppos** [comment]
> So should we expect that 'mil.no' and my.id' will return errors?

Yes, this is the expected behavior if you use this library. They are syntactically valid host names, but they are also public suffixes.
