### ISSUE TITLE
Ruby version upgrade should be major version upgrade

### ISSUE THREAD

**Issue by nikita-nikolajev** [weppos/publicsuffix-ruby#315]
ruby 2 to ruby 3 change should be a major version upgrade so <6 dependency does not suddenly break

**Comment by weppos** [comment]
> ruby 2 to ruby 3 change should be a major version upgrade so <6 dependency does not suddenly break

You are absolutely right. I generally do it, it slipped through the cracks this time. Let me address it now.

**Comment by eniomarques** [comment]
> > ruby 2 to ruby 3 change should be a major version upgrade so <6 dependency does not suddenly break
> 
> You are absolutely right. I generally do it, it slipped through the cracks this time. Let me address it now.

Indeed, thanks! addressable (used by git) has a <6.0 and it caused some problems :)
public_suffix (>= 2.0.2, < 6.0)

**Comment by weppos** [comment]
Both 5.1.1 (supporting Ruby 2.x) and 6.0.0 released.

**Comment by nikita-nikolajev** [comment]
thank you!
