### ISSUE TITLE
Support a way of adding a tld at runtime?

### ISSUE THREAD

**Issue by gnufied** [weppos/publicsuffix-ruby#37]
I don't know if you think it is a good idea, but what you think about ability to temporarily extend PublicSuffix with a new tld?

For example - lets say locally I have a domain called "foo.dev" which is not a valid TLD, but yet if I can say:

```ruby
PublicSuffix.add_tld = "dev"
domain =  PublicSuffix.parse("foo.dev")
.. no errors here
```

**Comment by jeroenj** [comment]
In that case we just do it like this:

```ruby
[1] pry(main)> PublicSuffix.valid?('foo.dev')
=> false
[2] pry(main)> PublicSuffix::List.default << PublicSuffix::Rule.factory('dev')`
=> # ...
[3] pry(main)> PublicSuffix.valid?('foo.dev')
=> true
```

I don't think an alternative way of doing this is really necessary?

**Comment by weppos** [comment]
Correct, you can append a new items at runtime [using `<<`](https://github.com/weppos/publicsuffix-ruby/blob/v1.5.3/lib/public_suffix/list.rb#L223-L228).

The method words on a list instance, therefore you can either use the `PublicSuffix::List.default` or any other instance of a list.
