### ISSUE TITLE
Uppercase domain is reported as not valid

### ISSUE THREAD

**Issue by jeremyhaile** [weppos/publicsuffix-ruby#62]
This fails:

```
PublicSuffix.parse('INSTAGRAM.COM')
PublicSuffix::DomainInvalid: `INSTAGRAM.COM' is not a valid domain
```

But this works:

```
PublicSuffix.parse('INSTAGRAM.COM'.downcase)
#<PublicSuffix::Domain:0x5c56a5e5 @sld="instagram", @tld="com", @trd=nil>
```

This seems unintuitive. If domain names need to be downcased before passing them into PublicSuffix, this should at least be more clearly documented in the README.

**Comment by weppos** [comment]
@jeremyhaile I created a patch in #66. There is a caveat: the returned domain will have all tokens lower cases, that means if you provide `INSTAGRAM.COM` as input, you will get as result

    #<PublicSuffix::Domain:0x5c56a5e5 @sld="instagram", @tld="com", @trd=nil>

Would that be a reasonable tradeoff?

**Comment by JakeAustwick** [comment]
Just a by-stander who found this issue while checking existing issues before using this library. I think the above is certainly a reasonable tradeoff, considering the case of a URL doesn't really matter anyway. Was this ever merged in, or should I still be calling downcase() before using the parse() method?

**Comment by jeremyhaile** [comment]
@weppos Sorry for taking a while to respond here, but I do think your tradeoff is worth it.

**Comment by pzb** [comment]
I've run into this as well, and agree that returning the normalized domain is not only a good tradeoff but the right thing.

**Comment by weppos** [comment]
Merged and released.
