### ISSUE TITLE
Make DEFAULT_DEFINITION_PATH configurable?

### ISSUE THREAD

**Issue by j-manu** [weppos/publicsuffix-ruby#69]
Right now, keeping publicsuffix-ruby up to date with the public suffix list in production is not easy. If we can have a configurable path to load definitions from, then we can decouple updating the gem from updating definitions cleanly.

**Comment by weppos** [comment]
The default configuration path is not configurable, however the `default` is.

```
PublicSuffix::List.default = PublicSuffix::List.parse('path/to/your/file')
```
