### ISSUE TITLE
Question about JRuby 1.7.19/Ruby 1.9.3 Support

### ISSUE THREAD

**Issue by diebels727** [weppos/publicsuffix-ruby#73]
I see that release 1.5.0 drops support for Ruby 1.9.3, and hence, Jruby 1.7.19, which we use.

I reviewed the v1.4.6..v1.5.0 diff, and I didn't see any obvious breaking change that requires Ruby 2.0.

Is there a known issue with Ruby 1.9.3 and v1.5.0?

**Comment by weppos** [comment]
1.9.3 doesn't include MiniTest. Vice-versa, Ruby 2.2 and head doesn't include TestUnit.
https://travis-ci.org/weppos/publicsuffix-ruby/jobs/41903139

I'm not planning to manage two test suites, therefore the bump to 2.x.
