### ISSUE TITLE
The internet is broken

### ISSUE THREAD

**Issue by mkcode** [weppos/publicsuffix-ruby#75]
Using public_suffix to parse incoming emails. The domain 'glow.sch.uk' is coming back as invalid, and unable to parse. This is correct behavior according to the registry, which lists '*.sch.uk'. 

Despite this, email addresses do exist on this domain. So... it's broken.

This a long-winded way to suggest that a soft parse method be available, which doesn't raise errors and tries to the best it can to split the domain into the tld, sld, and trd attributes.

Cheers!

**Comment by weppos** [comment]
@mkcode the validity of a domain depends on the rules defined by the [PSL](https://publicsuffix.org/). Moreover, `.UK` is one of those TLDs maintained officially by the corresponding registry (Nominet), therefore there is nothing I can do to fix that rule.

**Comment by mkcode** [comment]
Thanks for the quick response @weppos. I did check the PSL and this gem is giving the correct result.

I'm working on a project which is (for some reason) storing the domain parts individually, as output from the PublicSuffix.parse method. And therefore a soft parse method, which would split the domain even though it's invalid would be useful at the moment.

**Comment by mkcode** [comment]
I understand that this is outside of the scope of this project, and it's a bad idea to store domains in this fashion. Maybe there should a warning not to do this.
