### ISSUE TITLE
DomainNotAllowed Exception for AWS s3

### ISSUE THREAD

**Issue by krsyoung** [weppos/publicsuffix-ruby#76]
I'm currently receiving `PublicSuffix::DomainNotAllowed Exception` when trying to parse a S3 URL.  It seems like it should be valid and I do see it in the `definitions.txt`.  

Here is an example that causes the exception:

```ruby
url = 'https://s3.amazonaws.com/content.udacity-data.com/techdocs/UdacityCourseCatalogAPIDocumentation-v0.pdf'
uri = URI.parse(url)
#<URI::HTTPS https://s3.amazonaws.com/content.udacity-data.com/techdocs/UdacityCourseCatalogAPIDocumentation-v0.pdf>
uri.host
"s3.amazonaws.com"
domain = PublicSuffix.parse(uri.host)
*** PublicSuffix::DomainNotAllowed Exception: `s3.amazonaws.com' is not allowed according to Registry policy

nil
```

When tracing it seems the issue is here in that the `parts.join` is all of `s3.amazonaws.com` which makes the first `(.*)` fail to match anything in `rule.rb`.

```ruby
(byebug) domain
"s3.amazonaws.com"
(byebug) parts.join('\.')
"s3\\.amazonaws\\.com"
(byebug) domain.to_s.chomp(".") =~ /^(.*)\.(#{parts.join('\.')})$/
nil
(byebug) [$1, $2]
[nil, nil]
```
Is it expected that s3 would be rejected?  Thanks!

**Comment by weppos** [comment]
Yes, it's expected, it was requested by Amazon.
https://github.com/weppos/publicsuffix-ruby/blob/master/data/definitions.txt#L9526-L9528

If you want you can disable the private domain section.
https://github.com/weppos/publicsuffix-ruby#private-domains
