### ISSUE TITLE
Is www.google a valid domain?

### ISSUE THREAD

**Issue by matteomelani** [weppos/publicsuffix-ruby#80]
I am using version 1.5.1:

PublicSuffix.valid?('www.google') returns true.

This seems to be a bug since 'www.google' is not a valid domain. Is it not?

**Comment by matteomelani** [comment]
I have just checked the list and technically www.google is a valid domain.

**Comment by weppos** [comment]
Yes, because of [the new GOOGLE gTLD](https://github.com/whois/ianawhois/blob/master/GOOGLE), technically `www.google` is a valid domain.
