### ISSUE TITLE
Not recognizing public domain: rns.tn

### ISSUE THREAD

**Issue by nafmarcus** [weppos/publicsuffix-ruby#81]
-- PublicSuffix::DomainNotAllowed : `rns.tn' is not allowed according to Registry policy
As far as we can tell, it seems like rns.tn belongs to a tunesian ministry.

**Comment by weppos** [comment]
The suffix is restricted to registrations at the third level domain.
https://github.com/weppos/publicsuffix-ruby/blob/master/data/definitions.txt#L6053

**Comment by weppos** [comment]
I confirm the PSL definition is correct. According to [this document](http://www.registre.tn/upload/files/Charte_de_nommage__%20tn__24072013_FR.pdf) that's a reserved suffix and only third level domains are allowed.
