### ISSUE TITLE
PublicSuffix::DomainNotAllowed: `blogspot.com' is not allowed according to Registry policy

### ISSUE THREAD

**Issue by mdu4rt3** [weppos/publicsuffix-ruby#82]
2.2.1 :001 > d = parsed_domain = PublicSuffix.parse("blogspot.com")                                                                        
PublicSuffix::DomainNotAllowed: `blogspot.com' is not allowed according to Registry policy
        from /home/asdf/.rvm/gems/ruby-2.2.1/gems/public_suffix-1.4.6/lib/public_suffix.rb:71:in `parse'
        from (irb):1
        from /home/asdf/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
        from /home/asdf/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
        from /home/asdf/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/asdf/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/asdf//.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by weppos** [comment]
This is expected given blogspot is in the private domain section as requested by Google.
https://github.com/weppos/publicsuffix-ruby/blob/master/data/definitions.txt#L9953
