### ISSUE TITLE
Make it clear in README that the list is bundled with the gem

### ISSUE THREAD

**Issue by adamniedzielski** [weppos/publicsuffix-ruby#88]
This may sound a bit silly but when I initially looked at the README, it wasn't clear for me whether the gem comes with a bundled list or whether it makes requests to http://publicsuffix.org/

The ```data``` directory is quite meaningful when you take a look at it, but it may be good to mention "offline only" in the README. Would you like a PR?

**Comment by weppos** [comment]
@adamniedzielski it makes sense. Would you mind to propose a PR?
