### ISSUE TITLE
gov.kg is not allowed according to Registry policy

### ISSUE THREAD

**Issue by postmodern** [weppos/publicsuffix-ruby#90]
With public_suffix 1.5.3, [gov.kg](http://gov.kg) is not recognized as a valid domain, even though it's listed as a TLD in the Public Suffix List and has a website.

**Comment by weppos** [comment]
@postmodern this is expected. Here's the `.KG` definition:

```
// kg : http://www.domain.kg/dmn_n.html
kg
org.kg
net.kg
com.kg
edu.kg
gov.kg
mil.kg
```

This definition can be read as:

- allow any `(.*).kg`
- `(.*).(org|net|...|gov|mil).kg`
- disallow `org.kg`, `net.kg`, ..., `gov.kg`

Therefore, `gov.kg` itself is not considered a valid domain as `gov.kg` is itself a suffix. The longer rule takes precedence, hence `gov.kg` takes precedence over `kg`.

```ruby
➜  publicsuffix-ruby git:(master) rake console
irb -rubygems -I lib -r public_suffix.rb
2.3.0 :001 > PublicSuffix.valid?("foo.kg")
 => true
2.3.0 :002 > PublicSuffix.valid?("gov.kg")
 => false
2.3.0 :003 > PublicSuffix.("foo.kg")
2.3.0 :003 > PublicSuffix.parse("foo.kg")
 => #<PublicSuffix::Domain:0x007fe4cb0d6b20 @tld="kg", @sld="foo", @trd=nil>
2.3.0 :004 > PublicSuffix.parse("foo.gov.kg")
 => #<PublicSuffix::Domain:0x007fe4cb0dd358 @tld="gov.kg", @sld="foo", @trd=nil>
```

I hope this clarifies your question.
