### ISSUE TITLE
`krakow.pl' is not allowed according to Registry policy

### ISSUE THREAD

**Issue by static-max** [weppos/publicsuffix-ruby#93]
PublicSuffix::DomainNotAllowed: `krakow.pl' is not allowed according to Registry policy

But I can open the URL `http://krakow.pl/aktualnosci/195027,34,komunikat,maraton_dla_programistow_i_designerow_zbliza_sie_do_krakowa.html` in a browser with no problems, so is the browser wrong, or the parse-Method?

**Comment by weppos** [comment]
`krakow.pl` is a reserved .PL name, specifically a regional domain.

Actually, the interesting issue here is that that suffix is no longer considered a regional domain
https://www.dns.pl/english/dns-regiony.html
but it was grandfathered when the .PL list was reorganized.
https://github.com/publicsuffix/list/commit/7d3893d72c8edc90f2a9cc73c5a061749f18ebb6

I'm not sure why. I'll open a ticket at the PSL repo to check it.

**Comment by weppos** [comment]
https://github.com/publicsuffix/list/issues/146
