### ISSUE TITLE
Reading definition file fails when Encoding.default_internal is not UTF-8

### ISSUE THREAD

**Issue by static-max** [weppos/publicsuffix-ruby#94]
I'm forced to use `ASCII-8BIT` as internal and external encoding in my application. When I try to parse an URI, I get an error:

`
U+00E9 from UTF-8 to ASCII-8BIT
lib/public_suffix/list.rb:79
`
```
def self.default_definition
  File.open(DEFAULT_DEFINITION_PATH, "r:utf-8") { |f| f.read }
end
```

When I remove the utf-8 file encoding from _File.open_, the parsing seems to work as intended. Is the forced UTF-8 encoding needed? I did not find an Umlaut TLD in the definitions file.

**Comment by weppos** [comment]
@static-max it was for pre-2.0 Ruby versions. Given I don't support Ruby 1.9 anymore I can probably remove it as it's the default now.

I honestly can't guarantee that being forced to use ASCII-8BIT will not cause you some other troubles.

**Comment by weppos** [comment]
Changed. Travis is Happy, hence I'm happy too. :+1: 
https://travis-ci.org/weppos/publicsuffix-ruby

I'll deploy this change along with the various other pending changes in the upcoming release.

**Comment by static-max** [comment]
Hi Simone,

great, thanks a lot!
